=== api-evangelist/toast-tab/json-schema/partners-partner-access-external-webhook-rep-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/toast-tab/refs/heads/main/json-schema/partners-partner-access-external-webhook-rep-schema.json",
  "title": "PartnerAccessExternalWebhookRep",
  "description": "Information about a Toast platform restaurant.\n",
  "type": "object",
  "properties": {
    "restaurantGuid": {
      "type": "string",
      "format": "uuid",
      "description": "The unique Toast platform identifier for the restaurant.\n",
      "example": "e728cd53-2fa7-4e63-8f8f-93e78ea66b03"
    },
    "managementGroupGuid": {
      "type": "string",
      "format": "uuid",
      "description": "The unique Toast platform identifier for the management group\ncontaining the restaurant.\n",
      "example": "bdfda703-2a83-4e0f-9b8a-8ea0ee6cab79"
    },
    "restaurantName": {
      "type": "string",
      "description": "The human-readable name of the restaurant location.\n",
      "example": "Example Name"
    },
    "locationName": {
      "type": "string",
      "description": "The identifier of a specific restaurant location, set on the\n*Restaurant Info* page of Toast Web.\nFor example, a restaurant group might assign a location code\nsuch as `Location1234` to a specific location.\n",
      "example": "Location1234"
    },
    "externalGroupRef": {
      "type": "string",
      "description": "An identifier for the restaurant group that is recognized by your\nintegrated partner service. This information is entered by the\nrestaurant administrator. If you need information about the restaurant\ngroup in this data string, you instruct the restaurant administrator\nto enter it in the Toast platform configuration for the integration\npartner connection.\n",
      "example": "string"
    },
    "externalRestaurantRef": {
      "type": "string",
      "description": "An identifier for the restaurant location that is recognized by your\nintegrated partner service. This information is entered by the\nrestaurant administrator. If you need information about the restaurant\nlocation in this data string, you instruct the restaurant\nadministrator to enter it in the Toast platform configuration for the\nintegration partner connection.\n",
      "example": "string"
    },
    "modifiedDate": {
      "type": "integer",
      "format": "int64",
      "description": "The most recent date and time that the partner connection\nwas edited in epoch time (milliseconds since 1970-01-01 00:00:00).\n",
      "example": 1678846869551
    },
    "createdDate": {
      "type": "integer",
      "format": "int64",
      "description": "The date and time that the partner connection was created in epoch time (milliseconds since 1970-01-01 00:00:00).\n",
      "example": 1643858534451
    },
    "isoModifiedDate": {
      "type": "string",
      "description": "The most recent date and time that the partner connection\nwas edited in ISO8601 format.\n",
      "example": "2023-03-12T08:32:34.008000+00:00"
    },
    "isoCreatedDate": {
      "type": "string",
      "description": "The date and time that the partner connection was created in ISO8601 format.\n",
      "example": "2022-05-17T10:21:38.008000+00:00"
    },
    "createdByFirstName": {
      "type": "string",
      "description": "The first name of the restaurant employee who initiated the event.\n",
      "example": "Clemence"
    },
    "createdByLastName": {
      "type": "string",
      "description": "The last name of the restaurant employee who initiated the event.\n",
      "example": "Lefebvre"
    },
    "createdByEmailAddress": {
      "type": "string",
      "description": "The email address of the restaurant employee who connected the\nrestaurant to your integrated partner service, or who edited the\nconnection details.\n",
      "example": "clefebvre@mainstreetcafe.com"
    },
    "createdByPhoneNumber": {
      "type": "string",
      "description": "The phone number of the user who initiated the event.\n",
      "example": "9876543210"
    },
    "restaurantPhoneNumber": {
      "type": "string",
      "description": "The phone number of the restaurant.\n",
      "example": "8765432109"
    },
    "restaurantAddressLine1": {
      "type": "string",
      "description": "The physical address of the restaurant location.\n",
      "example": "123 Main Street"
    },
    "restaurantAddressLine2": {
      "type": "string",
      "description": "Optional additional physical address of the restaurant location.\n",
      "example": "Suite 321"
    },
    "restaurantCity": {
      "type": "string",
      "description": "The city in which the restaurant is located.\n",
      "example": "Gatineau"
    },
    "restaurantState": {
      "type": "string",
      "description": "The state in which the restaurant is located.\n",
      "example": "Massachusetts"
    },
    "restaurantZipCode": {
      "type": "string",
      "description": "The zip code of the restaurant location.\n",
      "example": "01234"
    },
    "restaurantLatitude": {
      "type": "string",
      "description": "The latitude of the restaurant location.\n",
      "example": "string"
    },
    "restaurantLongitude": {
      "type": "string",
      "description": "The longitude of the restaurant location.\n",
      "example": "string"
    },
    "restaurantCountryCode": {
      "type": "string",
      "description": "The ISO 3166-1 alpha-2 country code of the restaurant location.\n",
      "example": "US"
    },
    "restaurantTimezone": {
      "type": "string",
      "description": "The IANA time zone identifier of the restaurant location.\nFor example, `America/New_York`.\n",
      "example": "America/New_York"
    }
  }
}

=== api-evangelist/toast-tab/examples/partners-partner-access-external-webhook-rep-example.json
{
  "restaurantGuid": "e728cd53-2fa7-4e63-8f8f-93e78ea66b03",
  "managementGroupGuid": "bdfda703-2a83-4e0f-9b8a-8ea0ee6cab79",
  "restaurantName": "Example Name",
  "locationName": "Location1234",
  "externalGroupRef": "string",
  "externalRestaurantRef": "string",
  "modifiedDate": 1678846869551,
  "createdDate": 1643858534451,
  "isoModifiedDate": "2023-03-12T08:32:34.008000+00:00",
  "isoCreatedDate": "2022-05-17T10:21:38.008000+00:00",
  "createdByFirstName": "Clemence",
  "createdByLastName": "Lefebvre",
  "createdByEmailAddress": "clefebvre@mainstreetcafe.com",
  "createdByPhoneNumber": "9876543210",
  "restaurantPhoneNumber": "8765432109",
  "restaurantAddressLine1": "123 Main Street",
  "restaurantAddressLine2": "Suite 321",
  "restaurantCity": "Gatineau",
  "restaurantState": "Massachusetts",
  "restaurantZipCode": "01234",
  "restaurantLatitude": "string",
  "restaurantLongitude": "string",
  "restaurantCountryCode": "US",
  "restaurantTimezone": "America/New_York"
}
