=== api-evangelist/toast-tab/json-schema/partners-paginated-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/toast-tab/refs/heads/main/json-schema/partners-paginated-response-schema.json",
  "title": "PaginatedResponse",
  "description": "A wrapper object containing paginated sets of response data. The `results`\nvalue is an array of `PartnerAccessExternalRep` objects, which hold\ninformation about Toast platform restaurants. Also includes pagination\ndetails such as how many pages are included in the response, or the total\nnumber of objects in the `results` array.\n",
  "type": "object",
  "properties": {
    "currentPageNum": {
      "type": "integer",
      "description": "The active page within all repsonse pages. You can see the total amount of pages at the end of the response in the `lastPageNum` field.\n",
      "example": 12
    },
    "results": {
      "type": "array",
      "description": "An array of `PartnerAccessExternalRep` objects that include\ninformation about Toast platform restaurants.\n",
      "items": {
        "$ref": "#/$defs/PartnerAccessExternalRep"
      }
    },
    "totalResultCount": {
      "type": "integer",
      "description": "The total number of records returned.\n",
      "example": 1234
    },
    "pageSize": {
      "type": "integer",
      "description": "The number of restaurants returned in each page of response data.\n",
      "example": 100
    },
    "currentPageToken": {
      "type": "string",
      "description": "A string that identifies the current page of response data.\n",
      "example": "cDoxLHM6MQ=="
    },
    "nextPageToken": {
      "type": "string",
      "description": "A string that identifies the following page of response data.\n",
      "example": "cDoyLHM6MQ=="
    },
    "totalCount": {
      "type": "integer",
      "description": "The total number of results within the response record.\n",
      "example": 1234
    },
    "nextPageNum": {
      "type": "integer",
      "description": "The next available page in the data. `Null` if the current page of\nresults is the last available page.\n",
      "example": 14
    },
    "lastPageNum": {
      "type": "integer",
      "description": "The last page number in the response data.\n",
      "example": 13
    },
    "previousPageNum": {
      "type": "integer",
      "description": "The page number for the page previous to your current page in\nsequential order. `Null` if there are no pages previous to your\ncurrent page.\n",
      "example": 12
    }
  },
  "example": {
    "currentPageNum": 1,
    "results": [
      {
        "restaurantGuid": "7ab295f6-8dc8-4cb6-8cdb-072b83e84184",
        "managementGroupGuid": "75063706-dd6e-4da6-8bb6-3a99e218e686",
        "restaurantName": "Main Street Cafe",
        "locationName": "123 Main Street",
        "createdByEmailAddress": "clefebvre@mainstreetcafe.com",
        "externalGroupRef": "",
        "externalRestaurantRef": "",
        "modifiedDate": 1678823073353,
        "createdDate": 1678823073353,
        "isoModifiedDate": "2023-03-14T19:44:33.353Z",
        "isoCreatedDate": "2023-03-14T19:44:33.353Z"
      }
    ],
    "totalResultCount": 3222,
    "pageSize": 1,
    "currentPageToken": "cDoxLHM6MQ==",
    "nextPageToken": "cDoyLHM6MQ==",
    "totalCount": 3222,
    "nextPageNum": 2,
    "lastPageNum": 3222
  },
  "$defs": {
    "PartnerAccessExternalRep": {
      "type": "object",
      "description": "Information about a Toast platform restaurant.\n",
      "properties": {
        "restaurantGuid": {
          "type": "string",
          "format": "uuid",
          "description": "The unique Toast POS identifier for the restaurant.\n",
          "example": "e728cd53-2fa7-4e63-8f8f-93e78ea66b03"
        },
        "managementGroupGuid": {
          "type": "string",
          "format": "uuid",
          "description": "The guid of the management group containing the restaurant.\n",
          "example": "bdfda703-2a83-4e0f-9b8a-8ea0ee6cab79"
        },
        "deleted": {
          "type": "boolean",
          "description": "Indicates whether the restaurant is actively using the Toast \nplatform. For example, if a restaurant is no longer operating, \nor is no longer using the Toast platform, this value is `true`.\n",
          "example": true
        },
        "restaurantName": {
          "type": "string",
          "description": "The human-readable name of the restaurant location.\n",
          "example": "Main Street Cafe"
        },
        "locationName": {
          "type": "string",
          "description": "The identifier of a specific restaurant location, set on the \n*Restaurant Info* page of Toast Web. \nFor example, a restaurant group might assign a location code \nsuch as #1234 to a specific location.\n",
          "example": "123 Main Street"
        },
        "createdByEmailAddress": {
          "type": "string",
          "description": "The email address of the restaurant employee who connected the\nrestaurant to your integrated partner service, or who edited the\nconnection details.\n",
          "example": "clefebvre@mainstreetcafe.com"
        },
        "externalGroupRef": {
          "type": "string",
          "description": "An identifier for the restaurant group that is recognized by your\nintegrated partner service. This information is entered by the\nrestaurant administrator. If you need information about the restaurant\ngroup in this data string, you instruct the restaurant administrator\nto enter it in the Toast platform configuration for the integration\npartner connection.\n",
          "example": "string"
        },
        "externalRestaurantRef": {
          "type": "string",
          "description": "An identifier for the restaurant location that is recognized by your\nintegrated partner service. This information is entered by the\nrestaurant administrator. If you need information about the restaurant\nlocation in this data string, you instruct the restaurant\nadministrator to enter it in the Toast platform configuration for the\nintegration partner connection.\n",
          "example": "string"
        },
        "modifiedDate": {
          "type": "integer",
          "format": "int64",
          "description": "The most recent date and time that the partner connection\nwas edited in epoch time (milliseconds since 1970-01-01 00:00:00).\n",
          "example": 1678846869551
        },
        "createdDate": {
          "type": "integer",
          "format": "int64",
          "description": "The date and time that the partner connection was created in epoch\ntime (milliseconds since 1970-01-01 00:00:00).\n",
          "example": 1643858534451
        },
        "isoModifiedDate": {
          "type": "string",
          "description": "The most recent date and time that the partner connection\nwas edited in ISO8601 format.\n",
          "example": "2023-03-12T08:32:34.008000+00:00"
        },
        "isoCreatedDate": {
          "type": "string",
          "description": "The date and time that the partner connection was created in ISO8601\nformat.\n",
          "example": "2022-05-17T10:21:38.008000+00:00"
        }
      }
    }
  }
}

=== api-evangelist/toast-tab/examples/partners-paginated-response-example.json
{
  "currentPageNum": 1,
  "results": [
    {
      "restaurantGuid": "7ab295f6-8dc8-4cb6-8cdb-072b83e84184",
      "managementGroupGuid": "75063706-dd6e-4da6-8bb6-3a99e218e686",
      "restaurantName": "Main Street Cafe",
      "locationName": "123 Main Street",
      "createdByEmailAddress": "clefebvre@mainstreetcafe.com",
      "externalGroupRef": "",
      "externalRestaurantRef": "",
      "modifiedDate": 1678823073353,
      "createdDate": 1678823073353,
      "isoModifiedDate": "2023-03-14T19:44:33.353Z",
      "isoCreatedDate": "2023-03-14T19:44:33.353Z"
    }
  ],
  "totalResultCount": 3222,
  "pageSize": 1,
  "currentPageToken": "cDoxLHM6MQ==",
  "nextPageToken": "cDoyLHM6MQ==",
  "totalCount": 3222,
  "nextPageNum": 2,
  "lastPageNum": 3222
}
